version: '3'
services:
  db:
    image: mysql:8.benoit93260/mysql-server8.0.19command: --defauilt-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD